document.addEventListener('alpine:init', () => {
    Alpine.data('cheatSheet', () => ({
        search: '',
        keybindings: [
            // Neovim shortcuts
            { app: 'neovim', keybind: 'i', description: 'Insert mode (before cursor)', category: 'Modes' },
            { app: 'neovim', keybind: 'a', description: 'Insert mode (after cursor)', category: 'Modes' },
            { app: 'neovim', keybind: 'I', description: 'Insert mode (beginning of line)', category: 'Modes' },
            { app: 'neovim', keybind: 'A', description: 'Insert mode (end of line)', category: 'Modes' },
            { app: 'neovim', keybind: 'o', description: 'Open new line below', category: 'Modes' },
            { app: 'neovim', keybind: 'O', description: 'Open new line above', category: 'Modes' },
            { app: 'neovim', keybind: 'Esc', description: 'Exit insert mode', category: 'Modes' },
            { app: 'neovim', keybind: ':w', description: 'Save file', category: 'File' },
            { app: 'neovim', keybind: ':q', description: 'Quit', category: 'File' },
            { app: 'neovim', keybind: ':wq', description: 'Save and quit', category: 'File' },
            { app: 'neovim', keybind: ':q!', description: 'Force quit without saving', category: 'File' },
            { app: 'neovim', keybind: ':e file', description: 'Open/edit file', category: 'File' },
            { app: 'neovim', keybind: ':saveas file', description: 'Save as new file', category: 'File' },
            { app: 'neovim', keybind: 'dd', description: 'Delete line', category: 'Editing' },
            { app: 'neovim', keybind: 'yy', description: 'Yank (copy) line', category: 'Editing' },
            { app: 'neovim', keybind: 'p', description: 'Paste after cursor', category: 'Editing' },
            { app: 'neovim', keybind: 'P', description: 'Paste before cursor', category: 'Editing' },
            { app: 'neovim', keybind: 'u', description: 'Undo', category: 'Editing' },
            { app: 'neovim', keybind: 'Ctrl+r', description: 'Redo', category: 'Editing' },
            { app: 'neovim', keybind: '.', description: 'Repeat last command', category: 'Editing' },
            { app: 'neovim', keybind: 'x', description: 'Delete character', category: 'Editing' },
            { app: 'neovim', keybind: 'r', description: 'Replace character', category: 'Editing' },
            { app: 'neovim', keybind: 's', description: 'Substitute character', category: 'Editing' },
            { app: 'neovim', keybind: 'S', description: 'Substitute line', category: 'Editing' },
            { app: 'neovim', keybind: 'cc', description: 'Change line', category: 'Editing' },
            { app: 'neovim', keybind: 'C', description: 'Change to end of line', category: 'Editing' },
            { app: 'neovim', keybind: 'D', description: 'Delete to end of line', category: 'Editing' },
            { app: 'neovim', keybind: 'J', description: 'Join lines', category: 'Editing' },
            { app: 'neovim', keybind: 'gJ', description: 'Join lines without space', category: 'Editing' },
            { app: 'neovim', keybind: '>>', description: 'Indent line', category: 'Editing' },
            { app: 'neovim', keybind: '<<', description: 'Unindent line', category: 'Editing' },
            { app: 'neovim', keybind: '==', description: 'Auto-indent line', category: 'Editing' },
            { app: 'neovim', keybind: '~', description: 'Toggle case', category: 'Editing' },
            { app: 'neovim', keybind: 'gUU', description: 'Uppercase line', category: 'Editing' },
            { app: 'neovim', keybind: 'guu', description: 'Lowercase line', category: 'Editing' },
            { app: 'neovim', keybind: 'xp', description: 'Transpose characters', category: 'Editing' },
            { app: 'neovim', keybind: 'ciw', description: 'Change inner word', category: 'Text Objects' },
            { app: 'neovim', keybind: 'diw', description: 'Delete inner word', category: 'Text Objects' },
            { app: 'neovim', keybind: 'yiw', description: 'Yank inner word', category: 'Text Objects' },
            { app: 'neovim', keybind: 'viw', description: 'Select inner word', category: 'Text Objects' },
            { app: 'neovim', keybind: 'ci"', description: 'Change inside double quotes', category: 'Text Objects' },
            { app: 'neovim', keybind: 'di"', description: 'Delete inside double quotes', category: 'Text Objects' },
            { app: 'neovim', keybind: 'yi"', description: 'Yank inside double quotes', category: 'Text Objects' },
            { app: 'neovim', keybind: "ci'", description: 'Change inside single quotes', category: 'Text Objects' },
            { app: 'neovim', keybind: "di'", description: 'Delete inside single quotes', category: 'Text Objects' },
            { app: 'neovim', keybind: 'ci(', description: 'Change inside parentheses', category: 'Text Objects' },
            { app: 'neovim', keybind: 'cib', description: 'Change inside parentheses (b)', category: 'Text Objects' },
            { app: 'neovim', keybind: 'di(', description: 'Delete inside parentheses', category: 'Text Objects' },
            { app: 'neovim', keybind: 'dib', description: 'Delete inside parentheses (b)', category: 'Text Objects' },
            { app: 'neovim', keybind: 'ci[', description: 'Change inside brackets', category: 'Text Objects' },
            { app: 'neovim', keybind: 'di[', description: 'Delete inside brackets', category: 'Text Objects' },
            { app: 'neovim', keybind: 'ci{', description: 'Change inside braces', category: 'Text Objects' },
            { app: 'neovim', keybind: 'ciB', description: 'Change inside braces (B)', category: 'Text Objects' },
            { app: 'neovim', keybind: 'di{', description: 'Delete inside braces', category: 'Text Objects' },
            { app: 'neovim', keybind: 'diB', description: 'Delete inside braces (B)', category: 'Text Objects' },
            { app: 'neovim', keybind: 'cit', description: 'Change inside HTML tags', category: 'Text Objects' },
            { app: 'neovim', keybind: 'dit', description: 'Delete inside HTML tags', category: 'Text Objects' },
            { app: 'neovim', keybind: 'cip', description: 'Change inner paragraph', category: 'Text Objects' },
            { app: 'neovim', keybind: 'dip', description: 'Delete inner paragraph', category: 'Text Objects' },
            { app: 'neovim', keybind: 'yap', description: 'Yank around paragraph', category: 'Text Objects' },
            { app: 'neovim', keybind: 'yip', description: 'Yank inner paragraph', category: 'Text Objects' },
            { app: 'neovim', keybind: '>ip', description: 'Indent inner paragraph', category: 'Text Objects' },
            { app: 'neovim', keybind: '<ip', description: 'Unindent inner paragraph', category: 'Text Objects' },
            { app: 'neovim', keybind: '=ip', description: 'Auto-indent inner paragraph', category: 'Text Objects' },
            { app: 'neovim', keybind: 'gg', description: 'Go to first line', category: 'Navigation' },
            { app: 'neovim', keybind: 'G', description: 'Go to last line', category: 'Navigation' },
            { app: 'neovim', keybind: ':n', description: 'Go to line n', category: 'Navigation' },
            { app: 'neovim', keybind: 'w', description: 'Next word', category: 'Navigation' },
            { app: 'neovim', keybind: 'W', description: 'Next WORD (space-separated)', category: 'Navigation' },
            { app: 'neovim', keybind: 'b', description: 'Previous word', category: 'Navigation' },
            { app: 'neovim', keybind: 'B', description: 'Previous WORD (space-separated)', category: 'Navigation' },
            { app: 'neovim', keybind: 'e', description: 'End of word', category: 'Navigation' },
            { app: 'neovim', keybind: 'E', description: 'End of WORD', category: 'Navigation' },
            { app: 'neovim', keybind: 'ge', description: 'End of previous word', category: 'Navigation' },
            { app: 'neovim', keybind: '0', description: 'Start of line', category: 'Navigation' },
            { app: 'neovim', keybind: '^', description: 'First non-blank character', category: 'Navigation' },
            { app: 'neovim', keybind: '$', description: 'End of line', category: 'Navigation' },
            { app: 'neovim', keybind: 'g_', description: 'Last non-blank character', category: 'Navigation' },
            { app: 'neovim', keybind: 'h/j/k/l', description: 'Move left/down/up/right', category: 'Navigation' },
            { app: 'neovim', keybind: '{', description: 'Previous paragraph', category: 'Navigation' },
            { app: 'neovim', keybind: '}', description: 'Next paragraph', category: 'Navigation' },
            { app: 'neovim', keybind: '(', description: 'Previous sentence', category: 'Navigation' },
            { app: 'neovim', keybind: ')', description: 'Next sentence', category: 'Navigation' },
            { app: 'neovim', keybind: 'H', description: 'Top of screen', category: 'Navigation' },
            { app: 'neovim', keybind: 'M', description: 'Middle of screen', category: 'Navigation' },
            { app: 'neovim', keybind: 'L', description: 'Bottom of screen', category: 'Navigation' },
            { app: 'neovim', keybind: 'Ctrl+u', description: 'Half page up', category: 'Navigation' },
            { app: 'neovim', keybind: 'Ctrl+d', description: 'Half page down', category: 'Navigation' },
            { app: 'neovim', keybind: 'Ctrl+b', description: 'Full page up', category: 'Navigation' },
            { app: 'neovim', keybind: 'Ctrl+f', description: 'Full page down', category: 'Navigation' },
            { app: 'neovim', keybind: 'zz', description: 'Center cursor on screen', category: 'Navigation' },
            { app: 'neovim', keybind: 'zt', description: 'Cursor at top of screen', category: 'Navigation' },
            { app: 'neovim', keybind: 'zb', description: 'Cursor at bottom of screen', category: 'Navigation' },
            { app: 'neovim', keybind: '%', description: 'Matching bracket/paren', category: 'Navigation' },
            { app: 'neovim', keybind: '*', description: 'Search word under cursor (forward)', category: 'Search' },
            { app: 'neovim', keybind: '#', description: 'Search word under cursor (backward)', category: 'Search' },
            { app: 'neovim', keybind: 'g*', description: 'Search partial word (forward)', category: 'Search' },
            { app: 'neovim', keybind: 'g#', description: 'Search partial word (backward)', category: 'Search' },
            { app: 'neovim', keybind: '/pattern', description: 'Search forward', category: 'Search' },
            { app: 'neovim', keybind: '?pattern', description: 'Search backward', category: 'Search' },
            { app: 'neovim', keybind: 'n', description: 'Next search result', category: 'Search' },
            { app: 'neovim', keybind: 'N', description: 'Previous search result', category: 'Search' },
            { app: 'neovim', keybind: ':noh', description: 'Clear search highlighting', category: 'Search' },
            { app: 'neovim', keybind: ':s/old/new', description: 'Substitute first on line', category: 'Search' },
            { app: 'neovim', keybind: ':s/old/new/g', description: 'Substitute all on line', category: 'Search' },
            { app: 'neovim', keybind: ':%s/old/new/g', description: 'Substitute all in file', category: 'Search' },
            { app: 'neovim', keybind: ':%s/old/new/gc', description: 'Substitute with confirmation', category: 'Search' },
            { app: 'neovim', keybind: 'f{char}', description: 'Find char forward', category: 'Search' },
            { app: 'neovim', keybind: 'F{char}', description: 'Find char backward', category: 'Search' },
            { app: 'neovim', keybind: 't{char}', description: 'Till char forward', category: 'Search' },
            { app: 'neovim', keybind: 'T{char}', description: 'Till char backward', category: 'Search' },
            { app: 'neovim', keybind: ';', description: 'Repeat find forward', category: 'Search' },
            { app: 'neovim', keybind: ',', description: 'Repeat find backward', category: 'Search' },
            { app: 'neovim', keybind: '[[', description: 'Previous function/section', category: 'Search' },
            { app: 'neovim', keybind: ']]', description: 'Next function/section', category: 'Search' },
            { app: 'neovim', keybind: 'v', description: 'Visual mode (character)', category: 'Visual' },
            { app: 'neovim', keybind: 'V', description: 'Visual mode (line)', category: 'Visual' },
            { app: 'neovim', keybind: 'Ctrl+v', description: 'Visual block mode', category: 'Visual' },
            { app: 'neovim', keybind: 'gv', description: 'Reselect last visual', category: 'Visual' },
            { app: 'neovim', keybind: 'o', description: 'Switch visual cursor end', category: 'Visual' },
            { app: 'neovim', keybind: '>', description: 'Indent selection', category: 'Visual' },
            { app: 'neovim', keybind: '<', description: 'Unindent selection', category: 'Visual' },
            { app: 'neovim', keybind: '=', description: 'Auto-indent selection', category: 'Visual' },
            { app: 'neovim', keybind: 'c', description: 'Change selection', category: 'Visual' },
            { app: 'neovim', keybind: 'd', description: 'Delete selection', category: 'Visual' },
            { app: 'neovim', keybind: 'y', description: 'Yank selection', category: 'Visual' },
            { app: 'neovim', keybind: '~', description: 'Toggle case selection', category: 'Visual' },
            { app: 'neovim', keybind: 'U', description: 'Uppercase selection', category: 'Visual' },
            { app: 'neovim', keybind: 'u', description: 'Lowercase selection', category: 'Visual' },
            { app: 'neovim', keybind: 'ma', description: 'Set mark at a', category: 'Marks' },
            { app: 'neovim', keybind: 'mA', description: 'Set global mark at A', category: 'Marks' },
            { app: 'neovim', keybind: "'a", description: 'Go to mark a (line)', category: 'Marks' },
            { app: 'neovim', keybind: '`a', description: 'Go to mark a (exact)', category: 'Marks' },
            { app: 'neovim', keybind: "''", description: 'Back to previous line', category: 'Marks' },
            { app: 'neovim', keybind: '``', description: 'Back to previous position', category: 'Marks' },
            { app: 'neovim', keybind: '`.', description: 'Go to last change', category: 'Marks' },
            { app: 'neovim', keybind: "'[", description: 'Start of last change/yank', category: 'Marks' },
            { app: 'neovim', keybind: "']", description: 'End of last change/yank', category: 'Marks' },
            { app: 'neovim', keybind: ':marks', description: 'List all marks', category: 'Marks' },
            { app: 'neovim', keybind: 'Ctrl+w w', description: 'Switch window', category: 'Window' },
            { app: 'neovim', keybind: 'Ctrl+w h/j/k/l', description: 'Navigate windows', category: 'Window' },
            { app: 'neovim', keybind: 'Ctrl+w v', description: 'Split vertically', category: 'Window' },
            { app: 'neovim', keybind: 'Ctrl+w s', description: 'Split horizontally', category: 'Window' },
            { app: 'neovim', keybind: 'Ctrl+w c', description: 'Close window', category: 'Window' },
            { app: 'neovim', keybind: 'Ctrl+w o', description: 'Only this window', category: 'Window' },
            { app: 'neovim', keybind: 'Ctrl+w =', description: 'Equal window size', category: 'Window' },
            { app: 'neovim', keybind: 'Ctrl+w >', description: 'Increase width', category: 'Window' },
            { app: 'neovim', keybind: 'Ctrl+w <', description: 'Decrease width', category: 'Window' },
            { app: 'neovim', keybind: 'Ctrl+w +', description: 'Increase height', category: 'Window' },
            { app: 'neovim', keybind: 'Ctrl+w -', description: 'Decrease height', category: 'Window' },
            { app: 'neovim', keybind: 'Ctrl+]', description: 'Go to definition', category: 'Code' },
            { app: 'neovim', keybind: 'Ctrl+t', description: 'Jump back from def', category: 'Code' },
            { app: 'neovim', keybind: 'gd', description: 'Go to local declaration', category: 'Code' },
            { app: 'neovim', keybind: 'gD', description: 'Go to global declaration', category: 'Code' },
            { app: 'neovim', keybind: 'gf', description: 'Go to file under cursor', category: 'Code' },
            { app: 'neovim', keybind: 'gF', description: 'Go to file:line', category: 'Code' },
            { app: 'neovim', keybind: 'K', description: 'Show documentation', category: 'Code' },
            
            // Tmux shortcuts
            { app: 'tmux', keybind: 'Ctrl+b c', description: 'Create new window', category: 'Windows' },
            { app: 'tmux', keybind: 'Ctrl+b n', description: 'Next window', category: 'Windows' },
            { app: 'tmux', keybind: 'Ctrl+b p', description: 'Previous window', category: 'Windows' },
            { app: 'tmux', keybind: 'Ctrl+b w', description: 'List windows', category: 'Windows' },
            { app: 'tmux', keybind: 'Ctrl+b ,', description: 'Rename window', category: 'Windows' },
            { app: 'tmux', keybind: 'Ctrl+b &', description: 'Close window', category: 'Windows' },
            { app: 'tmux', keybind: 'Ctrl+b 0-9', description: 'Switch to window number', category: 'Windows' },
            { app: 'tmux', keybind: 'Ctrl+b l', description: 'Last active window', category: 'Windows' },
            { app: 'tmux', keybind: 'Ctrl+b %', description: 'Split pane vertically', category: 'Panes' },
            { app: 'tmux', keybind: 'Ctrl+b "', description: 'Split pane horizontally', category: 'Panes' },
            { app: 'tmux', keybind: 'Ctrl+b arrow', description: 'Navigate panes', category: 'Panes' },
            { app: 'tmux', keybind: 'Ctrl+b o', description: 'Next pane', category: 'Panes' },
            { app: 'tmux', keybind: 'Ctrl+b ;', description: 'Last active pane', category: 'Panes' },
            { app: 'tmux', keybind: 'Ctrl+b x', description: 'Close pane', category: 'Panes' },
            { app: 'tmux', keybind: 'Ctrl+b z', description: 'Zoom pane', category: 'Panes' },
            { app: 'tmux', keybind: 'Ctrl+b !', description: 'Break pane to window', category: 'Panes' },
            { app: 'tmux', keybind: 'Ctrl+b {', description: 'Swap pane left', category: 'Panes' },
            { app: 'tmux', keybind: 'Ctrl+b }', description: 'Swap pane right', category: 'Panes' },
            { app: 'tmux', keybind: 'Ctrl+b Space', description: 'Cycle layouts', category: 'Panes' },
            { app: 'tmux', keybind: 'Ctrl+b Alt+arrow', description: 'Resize pane', category: 'Panes' },
            { app: 'tmux', keybind: 'Ctrl+b d', description: 'Detach session', category: 'Sessions' },
            { app: 'tmux', keybind: 'Ctrl+b s', description: 'List sessions', category: 'Sessions' },
            { app: 'tmux', keybind: 'Ctrl+b $', description: 'Rename session', category: 'Sessions' },
            { app: 'tmux', keybind: 'Ctrl+b L', description: 'Switch to last session', category: 'Sessions' },
            { app: 'tmux', keybind: 'Ctrl+b (', description: 'Previous session', category: 'Sessions' },
            { app: 'tmux', keybind: 'Ctrl+b )', description: 'Next session', category: 'Sessions' },
            { app: 'tmux', keybind: 'Ctrl+b [', description: 'Enter copy mode', category: 'Copy' },
            { app: 'tmux', keybind: 'Ctrl+b ]', description: 'Paste', category: 'Copy' },
            { app: 'tmux', keybind: 'Ctrl+b =', description: 'Choose buffer', category: 'Copy' },
            { app: 'tmux', keybind: 'Ctrl+b -', description: 'Delete last buffer', category: 'Copy' },
            { app: 'tmux', keybind: 'Ctrl+b ?', description: 'Show all keybindings', category: 'Help' },
            { app: 'tmux', keybind: 'Ctrl+b :', description: 'Command mode', category: 'Help' },
            { app: 'tmux', keybind: 'Ctrl+b t', description: 'Show clock', category: 'Help' },
            { app: 'tmux', keybind: 'tmux new -s name', description: 'Create named session', category: 'Commands' },
            { app: 'tmux', keybind: 'tmux attach -t name', description: 'Attach to session', category: 'Commands' },
            { app: 'tmux', keybind: 'tmux ls', description: 'List sessions', category: 'Commands' },
            { app: 'tmux', keybind: 'tmux kill-session -t name', description: 'Kill session', category: 'Commands' },
            { app: 'tmux', keybind: 'tmux switch -t name', description: 'Switch to session', category: 'Commands' },
        ],

        get filteredKeybindings() {
            if (!this.search.trim()) {
                return this.keybindings;
            }
            const searchLower = this.search.toLowerCase();
            return this.keybindings.filter(kb => 
                kb.app.toLowerCase().includes(searchLower) ||
                kb.keybind.toLowerCase().includes(searchLower) ||
                kb.description.toLowerCase().includes(searchLower) ||
                kb.category.toLowerCase().includes(searchLower)
            );
        },

        get groupedByApp() {
            const groups = {};
            const items = this.search.trim() ? this.filteredKeybindings : this.keybindings;
            
            items.forEach(kb => {
                if (!groups[kb.app]) {
                    groups[kb.app] = {};
                }
                if (!groups[kb.app][kb.category]) {
                    groups[kb.app][kb.category] = [];
                }
                groups[kb.app][kb.category].push(kb);
            });
            
            return groups;
        },

        get searchResults() {
            return this.search.trim() ? this.filteredKeybindings : [];
        }
    }));
});
